### ISSUE TITLE
Replace django-guardian with model based permission system

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-api#54]
Once #50 is merged, we want to change the underlying method for storing workspace permissions from using django-guardian to a model, connecting users to workspaces with a role. This main reasons for this are:

1. Enforcing constraints in the database. With django-guardian, there's no way to enforce the permission constraints that we want _at the database level_, our only option is to attempt to enforce it using application logic, which is prone to error and edge cases. With a model, we can enforce these constraints at the database level, ensuring that any permissions which get into the database in the first place, must abide by the constraints that we set. These constraints are:
    1. Each user can only have one role assigned to them per workspace. 
    2. Each workspace should only have one owner, or in other words, the 'owner' role should only be assigned to one user per workspace.

2. Simplicity of app logic. Since we can leverage the above mentioned constraints, the app logic becomes much simpler. Instead of doing lots of checks and weird edge case handling, we can assert that our permission constraints are enforced, and focus on our application logic.

I've done some exploratory work on the [`permissions-with-model`](https://github.com/multinet-app/multinet-api/tree/permissions-with-model) branch, that can be used as a reference.

**Comment by waxlamp** [comment]
>    2. Each workspace should only have one owner, or in other words, the 'owner' role should only be assigned to one user per workspace.

I'd be more precise and say each workspace should have *exactly* one owner. Is that accurate?

**Comment by AlmightyYakob** [comment]
> I'd be more precise and say each workspace should have _exactly_ one owner. Is that accurate?

There's a bit of a fine line here. The constraint in question would be placed on the permissions model, let's say `WorkspacePermission`. This would be a [`UniqueConstraint`](https://docs.djangoproject.com/en/3.2/ref/models/constraints/#uniqueconstraint), which would ensure that any row with `owner` in the role column (any user assigned the 'owner' role) is unique per workspace. That is, every (`workspace`, `role=owner`) pairing is unqiue. To my knowledge, there's no constraint that we could place on the `WorkspacePermission` model to enforce that there's a (`workspace`, `owner`) row for every workspace that exists. So the enforcement that every workspace has a corresponding row with the `owner` role in the `WorkspacePermission` table would be entirely in our app logic.

From what I can tell, if we wanted to strictly enforce that each workspace always has exactly one owner, we'd simply need to add a required `owner` field to the `Workspace` model. This would change the permissions implementation, where each workspace has an owner, and then permissions to other users ( `maintainer`, `writer`, `reader`) can be granted through the `WorkspacePermission` table. Thinking about this for a minute, this actually make a lot of sense, and is more in line with how we naturally think about permissions. Instead of putting constraints on the `WorkspacePermission` model to have a special case for the `owner` role, they only contain the remaining roles, which can be assigned to any number of users. This would ensure that there are no orphaned workspaces. This would also add an extra step when checking a user's permission level, as we now need to check if they are the owner _or_ have a role assigned to them, but if we structure our queries correctly, this won't take any extra time, and won't add much complexity either.

Reflecting on this, I think I'm actually in favor of this new approach, as it further enforces the consistency we want at the database level. This also doesn't actually deviate from the permissions model proposed in the [RFC](https://github.com/multinet-app/multinet-rfcs/tree/master/0005-permissions_model), as it's just the implementation that's changing.

@waxlamp let me know what you think.

**Comment by naglepuff** [comment]
I'm in agreement with @AlmightyYakob here. I think having the `owner` be a field on the `workspace` model is the most natural way to model this restriction. If you look at the permissions-role-model branch, I've been able to move away from using `django-guardian` with relatively few changes. Changing how ownership is implemented would take some additional work but nothing too intensive, I don't think

**Comment by waxlamp** [comment]
Thanks for that deep dive, @AlmightyYakob, and good to know that you agree, @naglepuff.

I have two remaining concerns:
1. I don't want to keep extending the work that needs to be done here. If this change (to storing an owner with each workspace) is a small one, and it's the right choice, then there's no problem. If it's a bigger change, then we're still probably just fine (since our goal here is a robust implementation that we won't have to think much about in the future), but it's worth thinking about the level of effort. Can you give me an estimate on this?
2. Are we sure that we want to enforce that each workspace has a single, unique owner? I think that's the way we've been thinking about permissions, but there are two alternatives: first, that workspaces can have at least one owner--this seems obnoxious to me, especially when we have the maintainer permission already, which is able to do everything but delete a workspace; second, that workspaces can have no owner--this *kinda* makes sense for things like truly public datasets that nobody owns, but that we admins can still mess with. On thinking about it, neither of those alternatives really seems to offer much value. What do you think?

Both of these concerns are pretty minor I think. If you both agree, then let's go ahead with the required owner field on the workspace model.

Thanks for the analysis and discussion!

**Comment by naglepuff** [comment]
Changing how ownership is modeled is a relatively small change. I've actually got it mostly working locally right now. I'm updating tests to make sure they all run correctly, which is the biggest part of the change, but wrapping that up and doing some functional testing should take only a few more hours of work. 

 I agree with your conclusion in point 2, that the alternatives don't seem to offer much value, and they deviate from the RFC.

**Comment by AlmightyYakob** [comment]
Yeah, unless we have a concrete reason to modify the RFC, I don't think either of the options mentioned in your second point are worth pursuing. It looks like the permissions work is almost done, despite the rather long route we've taken.

**Comment by waxlamp** [comment]
Thanks guys. Go ahead and bring this in for a landing :)
