### ISSUE TITLE
Store column types that are specified on upload for later retrieval

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-api#83]
From Jake:
>We should probably store that data as a property (or association) of tables themselves.

**Comment by AlmightyYakob** [comment]
Since we want to be able to store an arbitrary number of "type annotations" for a given table, the following approach is what I had in mind

```python
class TableTypeAnnotation(TimeStampedModel):
	table = models.ForeignKey(Table, related_name='type_annotations', on_delete=models.CASCADE)
	column = models.CharField(max_length=255)
	type = models.CharField(choices=ColumnTypeEnum.values(), max_length=16)
	
	class Meta:
        constraints = [
            models.UniqueConstraint(fields=['table', 'column'], name='unique_column_type')
        ]
```

Then, to retrieve a tables type annotations, you could just do the following
```python
class Table:
	...
	@property
	def type_annotations(self):
		return TableTypeAnnotation.objects.filter(table=self)
```

And to turn this into JSON, you could do the following:

```python
table: Table
types_dict = {ann.column: ann.type for ann in table.type_annotations}
```

That last code snippet could also just go in the `type_annotations` property, if that seems best.
